# Build settings
markdown: kramdown

# baseurl - when publishing to github pages, this would be the URL of the repo.
# e.g., if you have username.github.io/my-awesome-repo, you'd put "/my-awesome-repo"
baseurl: ""

# your site URL goes here
# url: ""

port: 4000
exclude:
  - dev_assets
  - node_modules
  - package.json
  - gulpfile.js
  - README.md
  - config
  - npm-debug.log

# Plugins
gems:
  - jekyll-paginate

# How many posts to show per page
paginate: 5
